version: '2'
services:
  nginx:
    build: ./Nginx
    networks:
      app_net:
        ipv4_address: 19.18.18.2

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      app_net:
       ipv4_address: 19.18.18.4

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 19.18.18.0/16
        gateway: 19.18.18.1
